### ISSUE TITLE
Some models have not implemented "Type" of the resource

### ISSUE THREAD

**Issue by khurramar** [SidneyAllen/Xero-CFML#10]
/model/Address.cfc
/model/Phone.cfc

They were not entertaining the Type of respective resource. I had to implement **AddressType** and **PhoneType** in both of the components.

Otherwise, it creates/updates contact at Xero but leaves the **phones** and **addresses** unchanged. After making a little change in the above components, it was good to go.

I am not sure how many but I believe there will be more models. However I just made changes in the two for me as I needed them for my requirement.

**Comment by SidneyAllen** [comment]
Thanks - I've added those missing attributes to the models
