### ISSUE TITLE
Private App Invalid Oauth signature

### ISSUE THREAD

**Issue by phipps73** [SidneyAllen/Xero-CFML#11]
Just trying to implement the xero-cfml library with a Private Xero app and we are running into the following error when trying to make a call to: `account.getAll()`:

>oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature

Are private apps not currently supported?

**Comment by SidneyAllen** [comment]
Hi @phipps73 

I just ran the xero sample app using the private app configuration and it ran fine.

https://www.forgebox.io/view/xero-cfml-sample-app

You'll need to generate your pk8 key and upload a public key to http://app.xero.com.
https://github.com/SidneyAllen/Xero-CFML/blob/master/README.md#generate-public-private-key

Then create your config.json from app.xero.com. and store it in the "resources" folder along with the privatekey.pk8 file.  Mine looks like the following.

{ 
	"AppType" : "Private",
	"UserAgent" : "ColdFusion-Sid-S6XXXXXXXXXXXXXXXXXXXXXXXGE4",
	"ConsumerKey" : "S6XXXXXXXXXXXXXXXXXXXXXXXGE4",
	"ConsumerSecret" : "UJDXXXXXXXXXXXXXXXXXXXXXX9P5",
	"CallbackBaseUrl" : "http://localhost:8500",
	"CallbackPath" : "/xero-cfml-sample-app/callback.cfm",
	"PrivateKeyCert" :  "certs/privatekey.pk8"
}

Let me know how you get along

**Comment by phipps73** [comment]
Many thanks @SidneyAllen. The new config is working correctly. There was therefore nothing wrong with the private/public key generation. It was purely down to missing a few key attributes (CallbackBaseUrl and CallbackPath). Perhaps the readme could be updated?
