### ISSUE TITLE
Token Timestamp is 12-hour format w/o AM/PM, won't work after 12PM 

### ISSUE THREAD

**Issue by khurramar** [SidneyAllen/Xero-CFML#9]
/xero.cfc

function **IsTokeExpired** always returns **true** if called after 12PM of the day. That's because the function compares **tokenTimeStamp** with **Now()** datetime where one has 12hour date format (without AM/PM) and the other has 24 hour date format. Issue occurs when you run the code (for example) on 5:30PM, which is actually 17:30. xero.cfc stores the time in hh:nn:ss format without **tt** and when compared with Now() date it always fail because the code is running on 5:30PM and the token we stored has the expiry date as 5:30 in the morning. 

I fixed the code at my end and it worked fine. Just switched the small **hh** to capital **HH**

Line #185 `<cfset this.storage.setTimestamp('#DateFormat(now(), "mmm-dd-yyyy")# #TimeFormat(now(), "hh:mm:ss")#') >`
changed to `<cfset this.storage.setTimestamp('#DateFormat(now(), "mmm-dd-yyyy")# #TimeFormat(now(), "HH:mm:ss")#') >`

Line #246 `<cfset this.storage.setTimestamp('#DateFormat(now(), "mmm-dd-yyyy")# #TimeFormat(now(), "hh:mm:ss")#') >`
changed to `<cfset this.storage.setTimestamp('#DateFormat(now(), "mmm-dd-yyyy")# #TimeFormat(now(), "HH:mm:ss")#') >`

**Comment by khurramar** [comment]
two more changes in /model/

/model/Address.cfc
/model/Phone.cfc

They were not entertaining the Type of respective resource. I had to implement **AddressType** and **PhoneType** in both of the components. 

Otherwise, it creates/update contact at Xero but leaves the **phones** and **addresses** unchanged. After making a little change the above components, it was good to go.

**Comment by SidneyAllen** [comment]
Thanks - I've made the update
